### PR TITLE
Fix Windows 11 Acrylic effect Title Bar bug

### PR DESCRIPTION
**Pull request by Auties00**
After setting the acrylic effect on Windows 11 with the following code:
```
    await Window.setEffect(
      effect: WindowEffect.acrylic,
      color: Colors.transparent,
      dark: true
    );
```
Currently, the Window looks like this when focused:
Screenshot (24)

With my fix, it looks like this:
Screenshot (23)

This behaviour is coherent with the native behaviour, for example in the Settings app:
Screenshot (25)

I also created an enum for the DWMWINDOWATTRIBUTE values that the library needs.

### CODE REVIEW

**Comment by Adrian-Samoticha** [comment]
@alexmercerind Can you test this PR on your machine? I don’t have access to a Windows 11 machine.

**Comment by Auties00** [comment]
Any chance this could be merged?

**Comment by Adrian-Samoticha** [comment]
Alright, it seems that @alexmercerind isn’t really active these days (at least on this project), so maybe I’ll just merge and publish it anyway. @Auties00, have you checked that your fix doesn’t introduce any regressions on Windows 10?

**Comment by Auties00** [comment]
> Alright, it seems that @alexmercerind isn’t really active these days (at least on this project), so maybe I’ll just merge and publish it anyway. @Auties00, have you checked that your fix doesn’t introduce any regressions on Windows 10?

I've checked that and it doesn't cause any issues, yet I've noticed yesterday that if you have a WinSDK that defines the enumeration i added it will go in conflict. I'll push a fix for that

**Comment by NextdoorPsycho** [comment]
> > Alright, it seems that @alexmercerind isn’t really active these days (at least on this project), so maybe I’ll just merge and publish it anyway. @Auties00, have you checked that your fix doesn’t introduce any regressions on Windows 10?
> 
> I've checked that and it doesn't cause any issues, yet I've noticed yesterday that if you have a WinSDK that defines the enumeration i added it will go in conflict. I'll push a fix for that

ive tested and it works for me, not that a random on the internet can be any justification for merging it. but its a +1 from me

**Pull request merged**
